import { useState } from 'react'
import { generateRoadmapApi } from '../api'

const SKILL_OPTIONS = [
  'Python', 'Java', 'C++', 'JavaScript', 'React', 'FastAPI',
  'Django', 'LangChain', 'LangGraph', 'SQL', 'TensorFlow', 'PyTorch',
  'Node.js', 'Go', 'Rust', 'MongoDB', 'Docker', 'AWS',
]

const CONF_OPTIONS = ['not started', 'familiar', 'strong']

const priorityBadge = { high: '●', medium: '●', low: '●' }

export default function Roadmap() {
  const [form, setForm] = useState({
    year: '3rd year',
    branch: '',
    dsa_problems_solved: '50-150',
    known_skills: [],
    os_confidence: 'familiar',
    dbms_confidence: 'familiar',
    cn_confidence: 'familiar',
    oops_confidence: 'familiar',
    projects_count: 2,
    certifications: '',
    target_role: 'SDE',
    company_tier: 'Product-based (mid-tier)',
    placement_mode: 'On-campus',
    dream_companies: '',
    hours_per_week: 12,
    has_deadline: false,
    deadline: '',
    learning_style: 'Practice-first',
  })

  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [result, setResult] = useState(null)
  const [customSkillInput, setCustomSkillInput] = useState('')

  const update = (key, val) => setForm(prev => ({ ...prev, [key]: val }))

  const toggleSkill = (skill) => {
    setForm(prev => ({
      ...prev,
      known_skills: prev.known_skills.includes(skill)
        ? prev.known_skills.filter(s => s !== skill)
        : [...prev.known_skills, skill],
    }))
  }

  const addCustomSkill = () => {
    const skill = customSkillInput.trim()
    if (skill && !form.known_skills.includes(skill)) {
      setForm(prev => ({ ...prev, known_skills: [...prev.known_skills, skill] }))
    }
    setCustomSkillInput('')
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    setLoading(true)
    setError('')
    setResult(null)

    try {
      const payload = { ...form }
      if (!payload.has_deadline) payload.deadline = null
      delete payload.has_deadline
      if (!payload.certifications) delete payload.certifications
      if (!payload.dream_companies) delete payload.dream_companies

      const res = await generateRoadmapApi(payload)
      setResult(res.data)
    } catch (err) {
      setError(err.response?.data?.detail || err.message || 'Something went wrong.')
    } finally {
      setLoading(false)
    }
  }

  const handleReset = () => {
    setResult(null)
    setError('')
  }

  // ── Results view ──────────────────────────────────────────────────────────
  if (result) {
    const totalWeeks = result.phases.reduce((s, p) => s + p.duration_weeks, 0)
    return (
      <div className="roadmap-page">
        <div className="page-header">
          <h1>Your Placement Roadmap</h1>
          <p>Personalised plan generated by AI based on your profile</p>
        </div>

        {/* Gap summary */}
        <div className="rm-gap-card">
          <div className="rm-gap-label">Gap Analysis</div>
          <p>{result.gap_summary}</p>
        </div>

        {/* Meta badges */}
        <div className="rm-meta-row">
          <div className="rm-meta-badge">
            <span className="rm-meta-icon">T</span>
            <div>
              <div className="rm-meta-title">Weekly Commitment</div>
              <div className="rm-meta-value">{result.weekly_time_commitment}</div>
            </div>
          </div>
          <div className="rm-meta-badge">
            <span className="rm-meta-icon">D</span>
            <div>
              <div className="rm-meta-title">Total Duration</div>
              <div className="rm-meta-value">{totalWeeks} weeks</div>
            </div>
          </div>
          <div className="rm-meta-badge">
            <span className="rm-meta-icon">P</span>
            <div>
              <div className="rm-meta-title">Phases</div>
              <div className="rm-meta-value">{result.phases.length} phases</div>
            </div>
          </div>
        </div>

        {/* Phase timeline */}
        <h2 className="rm-section-title">Roadmap Phases</h2>
        <div className="rm-timeline">
          {result.phases.map((phase, i) => (
            <div key={i} className="rm-phase-card">
              <div className="rm-phase-header">
                <div className="rm-phase-number">{i + 1}</div>
                <div className="rm-phase-info">
                  <h3 className="rm-phase-name">
                    {phase.phase_name}
                    <span className="rm-priority-badge">
                      {priorityBadge[phase.priority] || '●'} {phase.priority}
                    </span>
                  </h3>
                  <span className="rm-phase-duration">{phase.duration_weeks} weeks</span>
                </div>
              </div>

              <div className="rm-phase-body">
                <div className="rm-phase-section">
                  <div className="rm-phase-label">Topics</div>
                  <div className="rm-phase-topics">
                    {phase.topics.map((t, j) => (
                      <span key={j} className="rm-topic-tag">{t}</span>
                    ))}
                  </div>
                </div>

                <div className="rm-phase-section">
                  <div className="rm-phase-label">Milestone</div>
                  <p className="rm-phase-text">{phase.milestone}</p>
                </div>

                {phase.suggested_project && (
                  <div className="rm-phase-section">
                    <div className="rm-phase-label">Suggested Project</div>
                    <p className="rm-phase-text rm-project-text">{phase.suggested_project}</p>
                  </div>
                )}

                <div className="rm-phase-section">
                  <div className="rm-phase-label">Why This Order</div>
                  <p className="rm-phase-text rm-why-text">{phase.why_this_order}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

        <button className="new-interview-btn" onClick={handleReset}>
          ← Generate Another Roadmap
        </button>
      </div>
    )
  }

  // ── Form view ─────────────────────────────────────────────────────────────
  return (
    <div className="roadmap-page">
      <div className="page-header">
        <h1>Placement Roadmap Generator</h1>
        <p>Tell us about yourself and we'll create a personalised preparation plan</p>
      </div>

      {error && <div className="error-message">{error}</div>}

      <form onSubmit={handleSubmit} className="rm-form">
        {/* Section 1: Current profile */}
        <div className="rm-form-section">
          <h3 className="rm-form-section-title">1. Where You Are Right Now</h3>
          <div className="rm-form-grid">
            <div className="form-group">
              <label className="form-label">Year</label>
              <select className="form-input" value={form.year} onChange={e => update('year', e.target.value)}>
                {['1st year', '2nd year', '3rd year', '4th year'].map(y => (
                  <option key={y} value={y}>{y}</option>
                ))}
              </select>
            </div>
            <div className="form-group">
              <label className="form-label">Branch</label>
              <input className="form-input" placeholder="e.g. AI & Data Science" value={form.branch} onChange={e => update('branch', e.target.value)} />
            </div>
            <div className="form-group">
              <label className="form-label">DSA Problems Solved</label>
              <select className="form-input" value={form.dsa_problems_solved} onChange={e => update('dsa_problems_solved', e.target.value)}>
                {['<50', '50-150', '150-300', '300+'].map(d => (
                  <option key={d} value={d}>{d}</option>
                ))}
              </select>
            </div>
            <div className="form-group">
              <label className="form-label">Projects Completed</label>
              <input className="form-input" type="number" min="0" max="50" value={form.projects_count} onChange={e => update('projects_count', parseInt(e.target.value) || 0)} />
            </div>
          </div>

          <div className="form-group">
            <label className="form-label">Known Languages / Frameworks</label>
            <div className="rm-skill-pills">
              {SKILL_OPTIONS.map(skill => (
                <button
                  type="button"
                  key={skill}
                  className={`rm-skill-pill ${form.known_skills.includes(skill) ? 'active' : ''}`}
                  onClick={() => toggleSkill(skill)}
                >
                  {skill}
                </button>
              ))}
              {/* Show custom-added skills that aren't in SKILL_OPTIONS */}
              {form.known_skills
                .filter(s => !SKILL_OPTIONS.includes(s))
                .map(skill => (
                  <button
                    type="button"
                    key={skill}
                    className="rm-skill-pill active"
                    onClick={() => toggleSkill(skill)}
                  >
                    {skill} ×
                  </button>
                ))}
            </div>
            <div className="rm-custom-skill-row">
              <input
                className="form-input"
                placeholder="Type a skill and press Enter…"
                value={customSkillInput}
                onChange={e => setCustomSkillInput(e.target.value)}
                onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); addCustomSkill() } }}
              />
              <button type="button" className="rm-add-skill-btn" onClick={addCustomSkill}>Add</button>
            </div>
          </div>

          <div className="form-group">
            <label className="form-label">Certifications (optional)</label>
            <input className="form-input" placeholder="e.g. AWS Cloud Practitioner" value={form.certifications} onChange={e => update('certifications', e.target.value)} />
          </div>

          <div className="form-group">
            <label className="form-label">CS Fundamentals Confidence</label>
            <div className="rm-conf-grid">
              {[
                { key: 'os_confidence', label: 'OS' },
                { key: 'dbms_confidence', label: 'DBMS' },
                { key: 'cn_confidence', label: 'CN' },
                { key: 'oops_confidence', label: 'OOP' },
              ].map(({ key, label }) => (
                <div key={key} className="rm-conf-item">
                  <span className="rm-conf-label">{label}</span>
                  <select className="form-input" value={form[key]} onChange={e => update(key, e.target.value)}>
                    {CONF_OPTIONS.map(c => (
                      <option key={c} value={c}>{c}</option>
                    ))}
                  </select>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Section 2: Target */}
        <div className="rm-form-section">
          <h3 className="rm-form-section-title">2. Where You Want to Go</h3>
          <div className="rm-form-grid">
            <div className="form-group">
              <label className="form-label">Target Role</label>
              <select className="form-input" value={form.target_role} onChange={e => update('target_role', e.target.value)}>
                {['SDE', 'AI/ML Engineer', 'Data Analyst', 'Data Scientist', 'Other'].map(r => (
                  <option key={r} value={r}>{r}</option>
                ))}
              </select>
            </div>
            <div className="form-group">
              <label className="form-label">Company Tier</label>
              <select className="form-input" value={form.company_tier} onChange={e => update('company_tier', e.target.value)}>
                {['Service-based', 'Product-based (mid-tier)', 'FAANG / top product', 'Startups'].map(t => (
                  <option key={t} value={t}>{t}</option>
                ))}
              </select>
            </div>
            <div className="form-group">
              <label className="form-label">Placement Mode</label>
              <div className="rm-radio-group">
                {['On-campus', 'Off-campus'].map(m => (
                  <button
                    type="button"
                    key={m}
                    className={`rm-radio-btn ${form.placement_mode === m ? 'active' : ''}`}
                    onClick={() => update('placement_mode', m)}
                  >
                    {m}
                  </button>
                ))}
              </div>
            </div>
            <div className="form-group">
              <label className="form-label">Dream Companies (optional)</label>
              <input className="form-input" placeholder="e.g. Google, Razorpay" value={form.dream_companies} onChange={e => update('dream_companies', e.target.value)} />
            </div>
          </div>
        </div>

        {/* Section 3: Constraints */}
        <div className="rm-form-section">
          <h3 className="rm-form-section-title">3. Your Constraints</h3>
          <div className="rm-form-grid">
            <div className="form-group">
              <label className="form-label">Hours Available Per Week</label>
              <input className="form-input" type="number" min="1" max="80" value={form.hours_per_week} onChange={e => update('hours_per_week', parseInt(e.target.value) || 1)} />
            </div>
            <div className="form-group">
              <label className="form-label">Learning Style</label>
              <select className="form-input" value={form.learning_style} onChange={e => update('learning_style', e.target.value)}>
                {['Videos', 'Docs', 'Practice-first', 'Mixed'].map(l => (
                  <option key={l} value={l}>{l}</option>
                ))}
              </select>
            </div>
          </div>
          <div className="form-group">
            <label className="rm-checkbox-label">
              <input type="checkbox" checked={form.has_deadline} onChange={e => update('has_deadline', e.target.checked)} />
              I have a fixed deadline
            </label>
            {form.has_deadline && (
              <input className="form-input rm-deadline-input" type="date" value={form.deadline} onChange={e => update('deadline', e.target.value)} />
            )}
          </div>
        </div>

        <button type="submit" className="generate-btn" disabled={loading}>
          {loading ? 'Generating Roadmap…' : 'Generate My Roadmap'}
        </button>
      </form>

      {loading && (
        <div className="loading-overlay">
          <div className="loading-spinner" />
          <p className="loading-message">Analyzing your profile and building your roadmap…</p>
        </div>
      )}
    </div>
  )
}
